name: Create Knapsack Report

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Generate new Knapsack report
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        KNAPSACK=true KNAPSACK_GENERATE_REPORT=true bundle exec rspec
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add knapsack_rspec_report.json
        git commit -m "Update knapsack_rspec_report.json"
    - name: Push changes
      run: git push origin HEAD:update-knapsack-report
